### ISSUE TITLE
UI for analyzer and output

### ISSUE THREAD

**Issue by chaaals** [Gidsss/UwUIDE#190]
## Specs
1. Modify `Run` button to execute `exe` to command prompt. The `Run` action button will only execute an `exe` file when compiled. Return an error if the program is not yet compiled.
2. Add action buttons: `Compile` and `Compile & Run`. `Compile` will be our new run action button. It will run lexer, syntax, analyzer and generate an `exe` file. `Compile & Run` will combine the compile and run processes.
3. Modify compiler logs to run checks on analyzer errors and display the compilation status.
4. Open and execute the generated exe file from the command prompt.

## Tasks 
- [x] Modify `Run` button to execute `exe` to command prompt
- [x] Add action buttons: `Compile` and `Compile & Run`
- [x] Modify compiler logs to run checks on analyzer errors
- [x] Open and execute the generated exe file from the command prompt

**Comment by chaaals** [comment]
I can take tasks 2 and 3 @Gidsss

**Comment by Gidsss** [comment]
> I can take tasks 2 and 3 @Gidsss

I'll take 1 and 4
