### ISSUE TITLE
Initial GUI for UwUIDE

### ISSUE THREAD

**Issue by chaaals** [Gidsss/UwUIDE#4]
## Description
Implement GUI code structure and 3 frames for `Code editor`, `Lexical analysis`, and `Console`. This will not integrate any functionality from lexer.

## Tasks
- [x] Install Custom Tkinter
- [ ] Gather IDE assets for the following: window icon, run, and console (add more if needed)
- [ ] Set a standard for the GUI code structure
- [ ] Implement `Code editor`, `Console`, and `Lexical analysis` frames

**Comment by Gidsss** [comment]
Is it also possible to add a button for quickly navigating to the next or previous error in the code? Suggestion lang to tho.

**Comment by HolyShaq** [comment]
I think pwede, may naiisip akong possible implementation. Pwede rin siguro, kapag hinover ung mouse sa token dun sa token list, ihihighlight niya sa code editor ung token naun. QoL lang naman mga eto tho, after ng functions isipin naten
